const questions = [
{
question:"日本が石油を多く輸入している国は？",
choices:["中国","サウジアラビア","ブラジル","タイ"],
answer:1
},
{
question:"鉄鉱石の主な輸入先は？",
choices:["オーストラリア","韓国","タイ","ドイツ"],
answer:0
},
{
question:"石炭の主な輸入先は？",
choices:["アメリカ","インド","オーストラリア","中国"],
answer:2
},
{
question:"ブラジルから多く輸入するものは？",
choices:["コーヒー豆","自動車","医薬品","天然ゴム"],
answer:0
},
{
question:"オーストラリアから多く輸入するものは？",
choices:["鉄鉱石","ぶどう酒","衣類","家具"],
answer:0
},
{
question:"中国から多く輸入するものは？",
choices:["衣類","石油","天然ガス","コーヒー"],
answer:0
},
{
question:"ドイツから多く輸入するものは？",
choices:["自動車","石炭","天然ゴム","木材"],
answer:0
},
{
question:"フランスから多く輸入するものは？",
choices:["ぶどう酒","石油","石炭","鉄鉱石"],
answer:0
},
{
question:"タイから多く輸入するものは？",
choices:["天然ゴム","鉄鉱石","石油","木材"],
answer:0
},
{
question:"サウジアラビアから多く輸入するものは？",
choices:["石油","木材","鉄鉱石","石炭"],
answer:0
},
{
question:"コメの生産量世界1位は？",
choices:["中国","日本","アメリカ","ブラジル"],
answer:0
},
{
question:"小麦の生産量世界1位は？",
choices:["中国","日本","タイ","韓国"],
answer:0
},
{
question:"トウモロコシの生産量世界1位は？",
choices:["アメリカ","中国","日本","ロシア"],
answer:0
},
{
question:"天然ゴムの生産が多い国は？",
choices:["タイ","カナダ","ドイツ","日本"],
answer:0
},
{
question:"コーヒー豆の生産量世界1位は？",
choices:["ブラジル","中国","日本","韓国"],
answer:0
},
{
question:"カカオ豆の生産量世界1位は？",
choices:["コートジボワール","中国","日本","タイ"],
answer:0
},
{
question:"オリーブの生産量が多い国は？",
choices:["スペイン","日本","中国","ロシア"],
answer:0
},
{
question:"羊毛の生産量が多い国は？",
choices:["オーストラリア","日本","韓国","タイ"],
answer:0
},
{
question:"漁獲量世界1位は？",
choices:["中国","日本","アメリカ","タイ"],
answer:0
},
{
question:"水産物を多く輸入している国は？",
choices:["日本","ブラジル","ロシア","韓国"],
answer:0
}
];
